// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import ()

type Person struct {
	Nic     string `json:"nic"`
	Address string `json:"address"`
	Name    string `json:"name"`
}
