name: Trigger auto deployment for address-check-test

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/address-check-test-AutoDeployTrigger-a36b84f5-910e-4412-ade5-d4c89d13c3b4.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: gramacheckservices.azurecr.io
          username: ${{ secrets.ADDRESSCHECKTEST_REGISTRY_USERNAME }}
          password: ${{ secrets.ADDRESSCHECKTEST_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: gramacheckservices.azurecr.io/gramacheck/address-check-test:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ADDRESSCHECKTEST_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n address-check-test -g asgardeo-intern-project --server gramacheckservices.azurecr.io --username  ${{ secrets.ADDRESSCHECKTEST_REGISTRY_USERNAME }} --password ${{ secrets.ADDRESSCHECKTEST_REGISTRY_PASSWORD }}
            az containerapp update -n address-check-test -g asgardeo-intern-project --image gramacheckservices.azurecr.io/gramacheck/address-check-test:${{ github.sha }}
